# Generated by Django 4.2.30 on 2026-05-09 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_destination', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_circuit', models.CharField(max_length=255)),
                ('duree', models.IntegerField(help_text='Nombre de jours')),
                ('distance_aller_km', models.FloatField(default=0, help_text='Distance simple aller (ex: 143 pour Andasibe)')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jour', models.IntegerField()),
                ('description_jour', models.TextField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='cotation.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_pax', models.IntegerField()),
                ('date_depart', models.DateField()),
                ('type_vehicule', models.CharField(help_text='ex: Sprinter', max_length=100)),
                ('conso_vehicule', models.FloatField(default=15, help_text='L/100km (ex: 15 pour Sprinter)')),
                ('auteur', models.CharField(max_length=100)),
                ('circuit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotation.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='ParametreGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.FloatField()),
                ('type_donnee', models.CharField(help_text='ex: decimal, entier', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_total', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('prix_vente_euro', models.FloatField()),
                ('taux_echange', models.FloatField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cotation.demandecotation')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('type_prestation', models.CharField(help_text='HOTEL, RESTO, VISITE, TRANSPORT', max_length=100)),
                ('base_prix', models.FloatField()),
                ('devise', models.CharField(default='MGA', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='cotation.cataloguedestination')),
            ],
        ),
        migrations.CreateModel(
            name='LignePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_par_defaut', models.FloatField(default=1)),
                ('unite', models.CharField(help_text='PAX, NUIT, JOUR, FORFAIT', max_length=50)),
                ('circuit_jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='cotation.circuitjour')),
                ('tarif_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotation.referencetarifaire')),
            ],
        ),
    ]
