# Generated by Django 4.2.30 on 2026-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametreglobal',
            options={'verbose_name': 'Paramètre Global', 'verbose_name_plural': 'Paramètres Globaux'},
        ),
        migrations.AlterField(
            model_name='circuit',
            name='distance_aller_km',
            field=models.FloatField(default=0, help_text='Distance simple aller'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='conso_vehicule',
            field=models.FloatField(default=15, help_text='L/100km'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='nb_pax',
            field=models.IntegerField(verbose_name='Nombre de personnes'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='type_vehicule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parametreglobal',
            name='cle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='parametreglobal',
            name='valeur',
            field=models.FloatField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='referencetarifaire',
            name='base_prix',
            field=models.FloatField(verbose_name='Prix de base'),
        ),
    ]
