# Generated by Django 4.2.30 on 2026-05-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotation', '0002_alter_parametreglobal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloguedestination',
            options={'verbose_name': 'Destination'},
        ),
        migrations.AlterModelOptions(
            name='demandecotation',
            options={'verbose_name': 'Demande de Cotation'},
        ),
        migrations.AlterModelOptions(
            name='referencetarifaire',
            options={'verbose_name': 'Référence Tarifaire'},
        ),
        migrations.AlterModelOptions(
            name='resultatcotation',
            options={'verbose_name': 'Résultat de la Cotation'},
        ),
        migrations.AlterField(
            model_name='cataloguedestination',
            name='nom_destination',
            field=models.CharField(max_length=100, unique=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='nom_circuit',
            field=models.CharField(max_length=255, verbose_name='Nom du Circuit'),
        ),
        migrations.AlterField(
            model_name='circuitjour',
            name='numero_jour',
            field=models.IntegerField(verbose_name='Jour n°'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='auteur',
            field=models.CharField(max_length=100, verbose_name='Établi par'),
        ),
        migrations.AlterField(
            model_name='ligneprestation',
            name='tarif_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotation.referencetarifaire', verbose_name='Prestation'),
        ),
        migrations.AlterField(
            model_name='referencetarifaire',
            name='libelle',
            field=models.CharField(max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='resultatcotation',
            name='cout_total',
            field=models.FloatField(verbose_name='Coût de revient'),
        ),
        migrations.AlterField(
            model_name='resultatcotation',
            name='prix_vente',
            field=models.FloatField(verbose_name='Prix de vente (MGA)'),
        ),
        migrations.AlterField(
            model_name='resultatcotation',
            name='prix_vente_euro',
            field=models.FloatField(verbose_name='Prix de vente (€)'),
        ),
        migrations.AlterField(
            model_name='resultatcotation',
            name='taux_echange',
            field=models.FloatField(verbose_name='Taux utilisé'),
        ),
    ]
